// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2gIEC1kz0ko02Ui0jg453Yb1dPGt0BSg',
    appId: '1:1093748930538:web:80b25f1166af3784a6e493',
    messagingSenderId: '1093748930538',
    projectId: 'event-manager-application',
    authDomain: 'event-manager-application.firebaseapp.com',
    storageBucket: 'event-manager-application.appspot.com',
    measurementId: 'G-VLYLFX4WQ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZobG_rSMidh75-NzfQ3zlOaqLhH5iht0',
    appId: '1:1093748930538:android:7e1ded538ee85a64a6e493',
    messagingSenderId: '1093748930538',
    projectId: 'event-manager-application',
    storageBucket: 'event-manager-application.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrA9wGzPDnr_2dNTbgWes5paOz3btHV54',
    appId: '1:1093748930538:ios:1aafc24e954b519da6e493',
    messagingSenderId: '1093748930538',
    projectId: 'event-manager-application',
    storageBucket: 'event-manager-application.appspot.com',
    iosBundleId: 'com.example.flutterApplication55',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrA9wGzPDnr_2dNTbgWes5paOz3btHV54',
    appId: '1:1093748930538:ios:e32491b0b1fd34b7a6e493',
    messagingSenderId: '1093748930538',
    projectId: 'event-manager-application',
    storageBucket: 'event-manager-application.appspot.com',
    iosBundleId: 'com.example.flutterApplication55.RunnerTests',
  );
}
